# Generated by Django 4.0.6 on 2022-08-11 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200, unique=True)),
                ('in_progress', models.BooleanField(default=True)),
                ('game_logs', models.JSONField(default=dict, verbose_name='ContactInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('damage', models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('damage', models.IntegerField(unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='game_app.game')),
                ('weapon', models.ManyToManyField(to='game_app.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('max_health', models.IntegerField(default=60)),
                ('health', models.IntegerField(default=60)),
                ('level', models.IntegerField(default=1)),
                ('type', models.CharField(default='monster', max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster', to='game_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_health', models.IntegerField(default=100)),
                ('health', models.IntegerField(default=100)),
                ('level', models.IntegerField(default=1)),
                ('money', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero', to='game_app.game')),
                ('skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.skills')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.weapon')),
            ],
        ),
    ]
