# Generated by Django 4.0.6 on 2022-08-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateGame',
            new_name='Game',
        ),
    ]
