# Generated by Django 4.0.6 on 2022-08-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_rename_creategame_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='status',
            new_name='in_progress',
        ),
    ]
