# Generated by Django 4.0.6 on 2022-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_rename_status_game_in_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='user_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
