# Generated by Django 4.0.6 on 2022-08-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='hero',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ManyToManyField(to='game_app.skills'),
        ),
    ]
