# Generated by Django 4.0.6 on 2022-08-10 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_remove_skills_hero_hero_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='skills',
        ),
        migrations.AddField(
            model_name='hero',
            name='skills',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.skills'),
        ),
    ]
