# Generated by Django 4.0.6 on 2022-08-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_remove_hero_skills_hero_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='type',
            field=models.CharField(default='monster', max_length=200),
        ),
    ]
